@startuml
title: Waardepapier Direct bevragen
footer: Waardepapieren.app
header: Waardepapieren.app
skinparam backgroundColor transparent

entity "Applicatie" as app #00377a
entity "Waardepapieren Service" as WP #fa4494

app -> WP: POST waardepapier (inc gegeven)
WP -> WP: Creërd waardepapier
WP -> APP: JSON van waardepapier (inc claim en pdf)

@enduml