@startuml
title: Waardepapieren Microservice
footer: Waardepapieren.app
header: Waardepapieren.app
skinparam backgroundColor transparent

database "Zaak registratie component" as ZRC #00377a
database "Document registratie component" as DRC #00377a
entity "Notificatie Component" as NC #00377a
entity "Waardepapieren Service" as WP #fa4494

ZRC -> NC: Notificeerd
NC -> WP: Notificeerd
WP -> ZRC: Haalt Zaak op
WP -> WP: Creerd waardepapier
WP -> DRC: Plaats waardepapier
WP -> ZRC: Zet status

@enduml