@startuml
title: StuF Waardepapier
footer: Waardepapieren.app
header: Waardepapieren.app
skinparam backgroundColor transparent

database "Zaak Systeem" as ZS #00377a
entity "StuF/ZGW Adapter" as Adapter #00377a
entity "Waardepapieren Service" as WP #fa4494

ZS -> Adapter: StuF Brug
Adapter -> WP: ZGW
WP -> WP: Creerd waardepapier
WP -> Adapter: Plaats waardepapier
Adapter -> ZS: Slaat ZGW om naar StuF
WP -> Adapter: Zet status
Adapter -> ZS: Slaat ZGW om naar StuF

@enduml