@startuml
title: ZDS Waardepapier
footer: Waardepapieren.app
header: Waardepapieren.app
skinparam backgroundColor transparent

database "Zaak Systeem" as ZS #00377a
entity "ZDS/ZGW Adapter" as Adapter #00377a
entity "Waardepapieren Service" as WP #fa4494

ZS -> Adapter: ZDS Brug
Adapter -> WP: ZGW
WP -> WP: Creerd waardepapier
WP -> Adapter: Plaats waardepapier
Adapter -> ZS: Slaat ZGW om naar ZDS
WP -> Adapter: Zet status
Adapter -> ZS: Slaat ZGW om naar ZDS

@enduml