@startuml
title: ZGW Waardepapier
footer: Waardepapieren.app
header: Waardepapieren.app


database "Zaak registratie component" as ZRC #00377a
database "Document registratie component" as DRC #00377a
entity "Notificatie Component" as NC #00377a
entity "Waardepapieren Service" as WP #fa4494
database "Haalcentraal BRP" as BRP #26b8e6

ZRC -> NC: Notificeerd
NC -> WP: Notificeerd
WP -> ZRC: Haalt Zaak op
WP -> BRP: Haalt Persoonsgegevens op
WP -> WP: Creerd waardepapier
WP -> DRC: Plaats waardepapier
WP -> ZRC: Zet status

@enduml