@startuml
title: ZGW Waardepapier
footer: Waardepapieren.app
header: Waardepapieren.app
skinparam backgroundColor transparent

actor Inwoner as Citizen #00377a
database "Zaak registratie component" as ZRC #00377a
database "Document registratie component" as DRC #00377a
entity "Notificatie Component" as NC #00377a
entity "Waardepapieren Service" as WP #fa4494
database "Haalcentraal BRP" as BRP #26b8e6

Citizen -> ZRC : Maakt Zaak aan (e.g. via web formulier)
ZRC -> NC: Notificeerd
NC -> WP: Notificeerd
WP -> ZRC: Haalt Zaak op
WP -> BRP: Haalt Persoonsgegevens op
WP -> WP: Creerd waardepapier
WP -> DRC: Plaats waardepapier
WP -> ZRC: Zet status
ZRC -> Citizen: Inwoner bekijkt zaak via Mijn Zaken
DRC -> Citizen: Inwoner bekijkt waardepapier via Mijn Zaken

@enduml