name: Deploy the Product Page to GitHub Pages

env: # Change these to your preferences any image url can also be a base encoded image
  GITHUB_PAGES_BRANCH: gh-pages

  # Connected Repository
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  GITHUB_REPOSITORY_URL: ${{ github.event.repository.url }}
  GITHUB_API_BASE_URL: https://api.github.com/repos/${{ github.repository }}/contents
  GITHUB_DOCS_DIRECTORY_PATHS: '[]'

  # Links
  SLACK_URL: "https://samenorganiseren.slack.com/archives/C049GJ0QNHW"
  READ_THE_DOCS_URL: "https://waardepapieren.readthedocs.io/en/latest/"

  # Navbar
  NAVBAR_LOGO_URL: "https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png"

  # Footer
  FOOTER_LOGO_URL: "https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png"
  FOOTER_LOGO_HREF: "https://dimapact.nl"

  # Jumbotron
  JUMBOTRON_TITLE: "Waardenpapieren"
  JUMBOTRON_SUBTITLE: "Het veilig, vertrouwd en snel verstrekken van digitale uittreksels en bewijsstukken"
  JUMBOTRON_DESCRIPTION: ${{ github.event.repository.description }}
  JUMBOTRON_SVG: "https://www.conduction.nl/wp-content/uploads/2021/07/cropped-Conduction_HOME_0000_afb1-1.png"

  # NL-Design Theme
  NL_DESIGN_THEME_CLASSNAME: "dimpact-theme"

  # Other
  FAVICON_URL: "https://openwebconcept.nl/wp-content/uploads/2019/07/cropped-Favicon-32x32.png"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the Product Website Template Code
        uses: actions/checkout@v2
        with:
          repository: ConductionNL/product-website-template
          ref: main

      # With special thanxs to https://github.com/SpicyPizza/create-envfile
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
          envkey_GATSBY_GITHUB_API_BASE_URL: ${{ env.GITHUB_API_BASE_URL }}
          envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ env.NL_DESIGN_THEME_CLASSNAME }}
          envkey_GATSBY_FAVICON_URL: ${{ env.FAVICON_URL }}
          envkey_GATSBY_NAVBAR_LOGO_URL: ${{ env.NAVBAR_LOGO_URL }}
          envkey_GATSBY_GITHUB_DOCS_DIRECTORY_PATHS: ${{ env.GITHUB_DOCS_DIRECTORY_PATHS }}
          envkey_GATSBY_READ_THE_DOCS_URL: ${{ env.READ_THE_DOCS_URL }}
          envkey_GATSBY_SLACK_URL: ${{ env.SLACK_URL }}
          envkey_GATSBY_GITHUB_REPOSITORY_URL: ${{ env.GITHUB_REPOSITORY_URL }}
          envkey_GATSBY_JUMBOTRON_TITLE: ${{ env.JUMBOTRON_TITLE }}
          envkey_GATSBY_JUMBOTRON_SUBTITLE: ${{ env.JUMBOTRON_SUBTITLE }}
          envkey_GATSBY_JUMBOTRON_DESCRIPTION: ${{ env.JUMBOTRON_DESCRIPTION }}
          envkey_GATSBY_JUMBOTRON_SVG: ${{ env.JUMBOTRON_SVG }}
          envkey_GATSBY_FOOTER_LOGO_URL: ${{ env.FOOTER_LOGO_URL }}
          envkey_GATSBY_FOOTER_LOGO_HREF: ${{ env.FOOTER_LOGO_HREF }}
          directory: pwa/static
          file_name: .env.production
          fail_on_empty: true
          sort_keys: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: cd pwa && npm install

      - name: Remove old Gatsby cache
        run: rm -rf pwa/.cache

      - name: Build application
        run: cd pwa && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: ${{ env.GITHUB_PAGES_BRANCH }}
          folder: pwa/public